# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mock_server import TSMService_pb2 as mock__server_dot_TSMService__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mock_server/TSMService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TSMServiceStub(object):
    """The core service for managing TSM sessions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSessions = channel.unary_unary(
                '/tsm.TSMService/ListSessions',
                request_serializer=mock__server_dot_TSMService__pb2.Empty.SerializeToString,
                response_deserializer=mock__server_dot_TSMService__pb2.SessionList.FromString,
                _registered_method=True)
        self.SwitchSession = channel.unary_unary(
                '/tsm.TSMService/SwitchSession',
                request_serializer=mock__server_dot_TSMService__pb2.SwitchRequest.SerializeToString,
                response_deserializer=mock__server_dot_TSMService__pb2.SwitchResponse.FromString,
                _registered_method=True)
        self.BackupSession = channel.unary_stream(
                '/tsm.TSMService/BackupSession',
                request_serializer=mock__server_dot_TSMService__pb2.BackupRequest.SerializeToString,
                response_deserializer=mock__server_dot_TSMService__pb2.BackupChunk.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/tsm.TSMService/GetMetrics',
                request_serializer=mock__server_dot_TSMService__pb2.Empty.SerializeToString,
                response_deserializer=mock__server_dot_TSMService__pb2.SystemMetrics.FromString,
                _registered_method=True)


class TSMServiceServicer(object):
    """The core service for managing TSM sessions
    """

    def ListSessions(self, request, context):
        """Retrieves a list of all available sessions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchSession(self, request, context):
        """Activates a specific session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackupSession(self, request, context):
        """Streams a backup of a specific session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Retrieves system performance and status metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TSMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=mock__server_dot_TSMService__pb2.Empty.FromString,
                    response_serializer=mock__server_dot_TSMService__pb2.SessionList.SerializeToString,
            ),
            'SwitchSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchSession,
                    request_deserializer=mock__server_dot_TSMService__pb2.SwitchRequest.FromString,
                    response_serializer=mock__server_dot_TSMService__pb2.SwitchResponse.SerializeToString,
            ),
            'BackupSession': grpc.unary_stream_rpc_method_handler(
                    servicer.BackupSession,
                    request_deserializer=mock__server_dot_TSMService__pb2.BackupRequest.FromString,
                    response_serializer=mock__server_dot_TSMService__pb2.BackupChunk.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=mock__server_dot_TSMService__pb2.Empty.FromString,
                    response_serializer=mock__server_dot_TSMService__pb2.SystemMetrics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tsm.TSMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tsm.TSMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TSMService(object):
    """The core service for managing TSM sessions
    """

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsm.TSMService/ListSessions',
            mock__server_dot_TSMService__pb2.Empty.SerializeToString,
            mock__server_dot_TSMService__pb2.SessionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsm.TSMService/SwitchSession',
            mock__server_dot_TSMService__pb2.SwitchRequest.SerializeToString,
            mock__server_dot_TSMService__pb2.SwitchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BackupSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tsm.TSMService/BackupSession',
            mock__server_dot_TSMService__pb2.BackupRequest.SerializeToString,
            mock__server_dot_TSMService__pb2.BackupChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsm.TSMService/GetMetrics',
            mock__server_dot_TSMService__pb2.Empty.SerializeToString,
            mock__server_dot_TSMService__pb2.SystemMetrics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
