# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import TSMService_pb2 as TSMService__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in TSMService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TSMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSessions = channel.unary_unary(
                '/tsm.TSMService/ListSessions',
                request_serializer=TSMService__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=TSMService__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.SwitchSession = channel.unary_unary(
                '/tsm.TSMService/SwitchSession',
                request_serializer=TSMService__pb2.SwitchSessionRequest.SerializeToString,
                response_deserializer=TSMService__pb2.SwitchSessionResponse.FromString,
                _registered_method=True)
        self.GetSessionDetails = channel.unary_unary(
                '/tsm.TSMService/GetSessionDetails',
                request_serializer=TSMService__pb2.GetSessionDetailsRequest.SerializeToString,
                response_deserializer=TSMService__pb2.GetSessionDetailsResponse.FromString,
                _registered_method=True)
        self.EncryptedSearch = channel.unary_unary(
                '/tsm.TSMService/EncryptedSearch',
                request_serializer=TSMService__pb2.EncryptedSearchRequest.SerializeToString,
                response_deserializer=TSMService__pb2.SearchResponse.FromString,
                _registered_method=True)


class TSMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncryptedSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TSMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=TSMService__pb2.ListSessionsRequest.FromString,
                    response_serializer=TSMService__pb2.ListSessionsResponse.SerializeToString,
            ),
            'SwitchSession': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchSession,
                    request_deserializer=TSMService__pb2.SwitchSessionRequest.FromString,
                    response_serializer=TSMService__pb2.SwitchSessionResponse.SerializeToString,
            ),
            'GetSessionDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionDetails,
                    request_deserializer=TSMService__pb2.GetSessionDetailsRequest.FromString,
                    response_serializer=TSMService__pb2.GetSessionDetailsResponse.SerializeToString,
            ),
            'EncryptedSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.EncryptedSearch,
                    request_deserializer=TSMService__pb2.EncryptedSearchRequest.FromString,
                    response_serializer=TSMService__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tsm.TSMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tsm.TSMService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TSMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsm.TSMService/ListSessions',
            TSMService__pb2.ListSessionsRequest.SerializeToString,
            TSMService__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsm.TSMService/SwitchSession',
            TSMService__pb2.SwitchSessionRequest.SerializeToString,
            TSMService__pb2.SwitchSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsm.TSMService/GetSessionDetails',
            TSMService__pb2.GetSessionDetailsRequest.SerializeToString,
            TSMService__pb2.GetSessionDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncryptedSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tsm.TSMService/EncryptedSearch',
            TSMService__pb2.EncryptedSearchRequest.SerializeToString,
            TSMService__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
